OoB Tp "permission"
MineInAbyss/DeeperWorld pull request #58
Opened 2021-04-16 08:16 UTC by Boy0000

Checks to see if player can tp between sections.
If /dw tp is set to off, player can tp with pearls and does not get affected by OoB damage.
Not sure if you want it as an actual permission but devboi

2021-04-16 08:19 UTC, Boy0000 commented
https://user-images.githubusercontent.com/62521371/114994604-3a4b4e80-9e9d-11eb-9239-9263d2fb71a3.mp4

2021-04-17 16:05 UTC, 0ffz requested changes

2021-04-17 16:05 UTC, 0ffz commented on src/main/java/com/derongan/minecraft/deeperworld/listeners/PlayerListener.kt
> +                && to?.section == null) && player.canMoveSections
Please follow the style of the other checks and add this one on a newline and without the brackets around all the previous ones. I also have a feeling you're using the old coding style which is what caused that extra spacing to be added in front of the `&&`s, see [here](https://github.com/MineInAbyss/MineInAbyss/wiki/Setup-and-Contribution-Guide#code-style-guide)

2021-04-18 16:57 UTC, 0ffz approved these changes

2021-04-18 16:57 UTC, merged